version: '3'
services:
  tabroom:
    container_name: tabroom
    image: tabroom:latest
    restart: always
    ports:
        - 80:80
    volumes:
      - /www/tabroom/web:/www/tabroom/web:rw
      - /www/profiles:/www/profiles
      - /etc/apache2/envvars:/etc/apache2/ennvars
      - /etc/apache2/sites-enabled/tabroom.com.conf:/etc/apache2/sites-enabled/tabroom.com.conf
      - /etc/apache2/mods-enabled/perl.conf:/etc/apache2/mods-enabled/perl.conf
      - /etc/apache2/mods-enabled/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
