version: '3'
services:
  tabroom:
    container_name: tabroom
    image: tabroom:latest
    restart: always
    ports:
        - 8888:80
    volumes:
      - /www/tabroom/web/lib/Tab/General.pm:/www/tabroom/web/lib/Tab/General.pm:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
