name: Tabroom API CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    CI: true
    TZ: "America/Chicago"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 18.2.0

    - name: Install packages
      run: npm install
      working-directory: ./api

    - name: Copy config file
      run: cp ./config/config.js.sample ./config/config.js
      working-directory: ./api

    - name: Lint
      run: npm run lint
      working-directory: ./api

    #- name: Tests
    #  run: npm run test
    #  working-directory: ./api

    - name: If tests passed change icon
      if: success()
      run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: speechanddebate/action-slack-notify@master
