name: Tabroom Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    CI: true
    REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Tag by commit
      id: get_version
      run: echo COMMIT_VERSION=$(echo $GITHUB_SHA) >> $GITHUB_ENV

    - name: Publish mason image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nsda/tabroom
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.speechanddebate.org
        tags: "${{ env.COMMIT_VERSION }}"

    - name: Publish indexcards image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nsda/indexcards
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.speechanddebate.org
        tags: "${{ env.COMMIT_VERSION }}"
        context: api

    - name: If image was published change icon
      if: success()
      run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    - name: Send slack notification
      uses: speechanddebate/action-slack-notify@master
